/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshPhysicalMaterial } from "three";
import { RigidBody } from "@react-three/rapier";

function Model(props) {
    const { nodes, materials } = useGLTF("/tube.glb");
    return (
        <RigidBody rotation={props.rotation} position={props.position} type="fixed" colliders='trimesh'  >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
            >
                <meshPhysicalMaterial
                    color={"white"}
                    roughness={0.2}
                    transparent={true}
                    opacity={1}
                />
            </mesh>
        </RigidBody>
    );
}

function Cylinder(props) {
    const { nodes, materials } = useGLTF("/cylinder.glb");
    return (
        <>
            <RigidBody scale={props.scale} rotation={props.rotation} position={props.position} type="fixed" colliders='trimesh'  >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder001.geometry}
                    // material={nodes.Cylinder001.material}
                >
                    <meshPhysicalMaterial transmission={1} transparent opacity={0.4}  roughness={0} thickness={0} envMapIntensity={4} />

                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder002.geometry}
                    // material={nodes.Cylinder002.material}
                >
                    <meshPhysicalMaterial transmission={1} roughness={0} thickness={3} envMapIntensity={4} />

                </mesh>
            </RigidBody>
        </>
    );
}

useGLTF.preload("/cylinder.glb");

const Tubes = () => {
    return (
        <group>
            <Model rotation={[0.3, 0, Math.PI * 0.6]} position={[4, -5, 0]} />
            <Model rotation={[0.3, 0, Math.PI * 0.4]} position={[1, -8, 0]} />
            <Cylinder scale={0.8} rotation={[0, 0, 0]} position={[4, -15, 0]} />
        </group>
    )
}
export default Tubes;

useGLTF.preload("/tube.glb");